### ISSUE TITLE
crashed while useing glowink sacs

### ISSUE THREAD

**Issue by quazi00** [gbl/ClickThrough#34]
i crashed while useing glow inksacks on a warped sign on a chest. I'm useing fabric: 0.14.25 using clickthrough-1.20-fabric0.83.0-0.4.1.jar
I was using complementary shaders but had them disabled and enabled with this crash
here is the list of mods I was using at the time of the crash:
yet-another-config-lib-fabric-3.2.1+1.20.2.jar"
XaerosWorldMap_1.35.0_Fabric_1.20.2.jar"
Xaeros_Minimap_23.9.3_Fabric_1.20.2.jar"
worldedit-mod-7.2.17.jar"
underwaterenchanting-1.20.2-2.5.jar"
tweakeroo-fabric-1.20.2-0.18.0.jar"
tweakermore-mc1.20.2-v3.15.1.jar"
trinkets-3.8.0.jar"
tradeuses-1.2.2-1.20.2-FABRIC.jar"
trade-cycling-fabric-1.20.2-1.0.7.jar"
status-effect-bars-1.0.4.jar"
spark-1.10.54-fabric.jar"
sodium-fabric-mc1.20.2-0.5.3.jar"
SimpleRPC-fabric-1.20-3.2.5.jar"
shulkerboxtooltip-fabric-4.0.7+1.20.2.jar"
screenshot-to-clipboard-1.0.9-fabric.jar"
quickcraft-1.2.5.jar"
noits-simple-sorting-0.6.0.jar"
MouseTweaks-fabric-mc1.20-2.25.jar"
modmenu-8.0.0.jar"
minihud-fabric-1.20.2-0.28.0.jar"
malilib-fabric-1.20.2-0.17.0.jar"
lithium-fabric-mc1.20.2-0.12.0.jar"
litematica-fabric-1.20.2-0.16.0.jar"
lapisreserve-1.0.8.jar"
lambdynamiclights-2.3.3+1.20.2.jar.disabled"
jei-1.20.2-fabric-16.0.0.28.jar"
jamlib-fabric-1.20.2-1.0.3+1.20.2.jar"
iris-mc1.20.2-1.6.14.jar"
iris-mc1.20.2-1.6.10 (1).jar"
harvestwithease-1.20.2-8.0.0.2-fabric.jar"
ForgeConfigAPIPort-v9.1.2-1.20.2-Fabric.jar"
feather_trampling-1.0.2-1.20.2.jar"
fallingleaves-1.15.4+1.20.1.jar"
fabric-language-kotlin-1.10.16+kotlin.1.9.21.jar"
fabric-api-0.91.2+1.20.2.jar"
extremesoundmuffler-3.43-fabric-1.20.2.jar"
elytra-chestplate-swapper-1.3.0-MC1.20.jar"
deepslatecutting-fabric-1.7.0.jar"
dark-loading-screen-1.6.14.jar"
CreativeCore_FABRIC_v2.11.2_mc1.20.2.jar"
CraterLib-Fabric-1.20.2-1.0.3.jar"
collective-1.20.2-7.16.jar"
Clumps-fabric-1.20.2-13.0.0.4.jar"
cloth-config-12.0.113-fabric.jar"
clickthrough-1.20-fabric0.83.0-0.4.1.jar."
cherishedworlds-fabric-7.0.1+1.20.2.jar"
charmofundying-fabric-7.0.0+1.20.2.jar"
bundlesunlocked-v1.0.12-fabric-1.20.2.jar"
bsvsb-3.0.3.jar"
borderless-mining-1.1.9+1.20.2.jar"
boosted-brightness-2.2.1.jar"
BetterF3-8.0.2-Fabric-1.20.2.jar"
architectury-10.0.17-fabric.jar"
appleskin-fabric-mc1.20.2-2.5.1.jar"
3dskinlayers-fabric-1.5.6-mc1.20.2.jar"
dynamiclights-v1.7-mc1.17x-1.20x-mod"

**Comment by gbl** [comment]
Without the complete crash log, especially the stack trace, I can't do anything. But I'd assume it's some incompatibility because ClickThrough doesn't support 1.20.2.

**Comment by kawashirov** [comment]
Yea, clicking any dye on 1.20.2 causes crash with this error:
```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2024-01-04 09:56:38
Description: Unexpected error

java.lang.NoSuchMethodError: 'void net.minecraft.client.network.ClientPlayNetworkHandler.method_2883(net.minecraft.network.packet.Packet)'
	at MC//net.minecraft.client.MinecraftClient.switchCrosshairTarget(MinecraftClient.java:9179)
	at MC//net.minecraft.client.MinecraftClient.handler$bdf000$clickthrough$switchCrosshairTargetItemUse(MinecraftClient.java:9113)
	at MC//net.minecraft.client.MinecraftClient.doItemUse(MinecraftClient.java:1824)
	at MC//net.minecraft.client.MinecraftClient.handleInputEvents(MinecraftClient.java:2102)
	at MC//net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:1933)
	at MC//net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1237)
	at MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at app//org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at app//org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at app//org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```
(deobfuscated stacktrace)

I using `clickthrough-1.20-fabric0.83.0-0.4.1.jar`
All other features actually works well even if it's incompatible version.
